# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.11.4

pipelines:
#  default:
#    - step:
#        caches:
#          - node
#        script: # Modify the commands below to build your repository.
#          - cd server
#          - npm install
#          - npm test
#        services:
#          - mongo
  branches:
      staging:
#        - step:
#            name: Run server unit tests
#            caches:
#              - node
#            script:
#              - cd server
#              - npm install
#              - npm test
#            services:
#              - mongo
        - step:
            name: Deploy server and client to staging
            deployment: staging
            trigger: automatic
            script:
              - cd scripts
              - npm install
              - cd ../
              - node scripts/server.js staging
              - node scripts/client.js staging
#      master:
      hotfix-master:
#        - step:
#            name: Run server unit tests
#            caches:
#              - node
#            script:
#              - cd server
#              - npm install
#              - npm test
#            services:
#              - mongo
        - step:
            name: Deploy server and client to production
            deployment: production
#            trigger: manual
            script:
              - cd client
              - npm version
              - npm root -g
              - node -v
#              - ls /usr/local/lib/node_modules/
#              - ls /usr/local/lib/node_modules/@angular
#              - ls /usr/local/lib/node_modules/@angular/cli
#              - ls /usr/local/lib/node_modules/@angular/cli/bin
              - npm install -g @angular/cli
              - alias ng="/usr/local/lib/node_modules/@angular/cli/bin/ng"
              - ng -v
#              - npm link @angular/cli
#              - ng update @angular/cli --migrate-only --from=1.7.4
              - cd ../scripts
              - npm install
              - cd ../
              - node scripts/client.js production
              - node scripts/server.js production

definitions:
  services:
    mongo:
      image: mongo:3.6.8