# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.11.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - cd server
          - npm install
          - npm test
        services:
          - mongo
  branches:
      T340-bitbucket-continuous-integration:
        -step:
          caches:
            - node
          script:
            - cd server
            - npm install
            - npm test
          services:
            - mongo
        - step:
            script:
              - echo "This script runs only on commit to the T340-bitbucket-continuous-integration branch."

definitions:
  services:
    mongo:
      image: mongo:3.6.8