# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.11.4

pipelines:
  branches:
      staging:
       - step:
           name: Run server unit tests
           caches:
             - node
           script:
             - cd server
             - npm install
             - npm test
           services:
             - mongo
       - step:
            name: Deploy server and client to staging
            deployment: staging
            trigger: automatic
            script:
              - cd scripts
              - npm install
              - cd ../
              - node scripts/client.js staging
              - node scripts/server.js staging
      master:
        - step:
            name: Run server unit tests
            caches:
              - node
            script:
              - cd server
              - npm install
              - npm test
            services:
              - mongo
        - step:
            name: Deploy server and client to production
            deployment: production
            trigger: manual
            script:
              - cd client
              - npm install
              - npm install -g @angular/cli
              - cd ../scripts
              - npm install
              - cd ../
              - node scripts/client.js production
              - node scripts/server.js production
options:
  max-time: 20

definitions:
  services:
    mongo:
      image: mongo:3.6.8
